# Generated by Django 3.2.12 on 2025-12-18 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace_management', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial_squashed_0004_added_history_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('app_installation', 'Установка приложения'), ('app_uninstallation', 'Удаление приложения'), ('app_moderation', 'Модерация'), ('policy_change', 'Изменение политик'), ('app_update', 'Обновление приложения'), ('organization_create', 'Создание организации'), ('organization_update', 'Обновление организации'), ('circle_create', 'Создание кружка'), ('circle_update', 'Обновление кружка'), ('user_login', 'Вход пользователя'), ('user_logout', 'Выход пользователя'), ('system_event', 'Системное событие')], max_length=50, verbose_name='Тип события')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID объекта')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='marketplace_management.app', verbose_name='Приложение')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог аудита',
                'verbose_name_plural': 'Логи аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='audit_audit_event_t_4496ba_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['app'], name='audit_audit_app_id_827f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization'], name='audit_audit_organiz_b2fceb_idx'),
        ),
    ]
