# Generated by Django 3.2.12 on 2024-04-24 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='sender_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comment_sender_ct', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='sender_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
