# Generated by Django 3.2.12 on 2024-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20240424_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_internal_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
