# Generated by Django 3.2.12 on 2024-05-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tickets', '0003_ticketcomment_is_internal_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='sender_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comment_sender_ct', to='contenttypes.contenttype'),
        ),
    ]
