from typing import Any

HARD_DELETE: int
SOFT_DELETE: int
SOFT_DELETE_CASCADE: int
HARD_DELETE_NOCASCADE: int
NO_DELETE: int
DELETED_INVISIBLE: int
DELETED_VISIBLE_BY_FIELD: int
DELETED_VISIBLE_BY_PK: int
DELETED_ONLY_VISIBLE: int
DELETED_VISIBLE: int
FIELD_NAME: str
DELETED_BY_CASCADE_FIELD_NAME: str
