# Generated by Django 3.2.12 on 2026-06-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
