# Generated by Django 3.2.12 on 2026-01-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="installed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
