# Generated by Django 3.2.12 on 2026-06-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='optional_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='app',
            name='required_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='installation',
            name='granted_scopes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='oauth2token',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
