# Generated by Django 3.2.12 on 2026-06-02 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='type',
        ),
        migrations.AddField(
            model_name='app',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='app',
            name='grant_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='app',
            name='manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='app',
            name='redirect_uris',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='app',
            name='response_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token_type', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('refresh_token', models.CharField(max_length=255, unique=True)),
                ('expires_in', models.IntegerField()),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OAuth2AuthorizationCode',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('redirect_uri', models.URLField()),
                ('auth_time', models.DateTimeField(auto_now_add=True)),
                ('response_type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
