# Generated by Django 3.2.12 on 2026-06-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_management', '0002_auto_20260604_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='app',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
