# Generated by Django 3.2.12 on 2026-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_management', '0002_auto_20260604_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2authorizationcode',
            name='code_challenge',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='oauth2authorizationcode',
            name='code_challenge_method',
            field=models.CharField(blank=True, default='S256', max_length=10),
        ),
    ]
