# Generated by Django 3.2.12 on 2026-01-17 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_management", "0002_auto_20260112_1930"),
        ("marketplace_management", "0003_auto_20260117_1439"),
    ]

    operations = []
