# Generated by Django 3.2.12 on 2026-06-07 14:34

from django.db import migrations


def migrate_category_names(apps, schema_editor):
    App = apps.get_model('marketplace_management', 'App')
    Category = apps.get_model('marketplace_management', 'Category')
    
    for app in App.objects.all():
        if app.category_name:
            category, _ = Category.objects.get_or_create(name=app.category_name)
            app.category = category
            app.save(update_fields=['category'])

def reverse_migrate(apps, schema_editor):
    App = apps.get_model('marketplace_management', 'App')
    
    for app in App.objects.all():
        if app.category:
            app.category_name = app.category.name
            app.save(update_fields=['category_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_management', '0003_auto_20260607_1434'),
    ]

    operations = [
        migrations.RunPython(migrate_category_names, reverse_migrate)
    ]
