# Generated by Django 3.2.12 on 2026-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "marketplace_management",
            "0004_merge_0002_auto_20260112_1930_0003_auto_20260117_1439",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("active", "active"),
                    ("uninstalled", "uninstalled"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="installation",
            unique_together=set(),
        ),
    ]
