# Generated by Django 3.2.12 on 2026-06-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_management', '0004_migrate_category_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='category_name',
        ),
    ]
