# Generated by Django 3.2.12 on 2026-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_management', '0005_remove_app_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='eula_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='app',
            name='privacy_policy_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
