# Generated by Django 3.2.12 on 2026-01-17 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_management", "0005_auto_20260117_2027"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
