# Generated by Django 3.2.12 on 2026-01-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace_management", "0006_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="marketplace_management.app",
            ),
        ),
    ]
