# Generated by Django 3.2.12 on 2022-12-29 20:56

import config.settings.object_storage
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import rules.contrib.models
import uuid


class Migration(migrations.Migration):

    replaces = [('students', '0002_auto_20220831_2005'), ('students', '0003_studentprofile_photo')]

    dependencies = [
        ('students', '0001_initial_squashed_0005_alter_studentprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileCircleAdditional',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('student_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=17, null=True, region=None, verbose_name='telephone number')),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=17, null=True, region=None, verbose_name='telephone number')),
                ('parent_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=17, null=True, region=None, verbose_name='telephone number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, storage=config.settings.object_storage.ClientDocsStorage(), upload_to=''),
        ),
    ]
