# Generated by Django 3.2.12 on 2022-09-18 18:05

import config.settings.object_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220831_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, storage=config.settings.object_storage.ClientDocsStorage(), upload_to=''),
        ),
    ]
