# Generated by Django 3.2.12 on 2022-07-12 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        ('students', '0002_auto_20220707_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('circle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='circles.circle')),
                ('student_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
