# Generated by Django 3.2.12 on 2023-03-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial_squashed_0004_refactoring_history'),
        ('students', '0005_alter_studentprofile_age_squashed_0008_refactoring_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='photos.photo'),
        ),
    ]
