# Generated by Django 3.2.12 on 2022-11-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_added_history_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudentprofilecircleadditional',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalStudent',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentProfileCircleAdditional',
        ),
    ]
