# Generated by Django 3.2.12 on 2022-07-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        ('student', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='circles.circle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.studentprofile'),
        ),
    ]
