# Generated by Django 3.2.12 on 2022-07-06 15:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('parent_profiles', models.ManyToManyField(related_name='parent_families', to='parents.ParentProfile')),
                ('student_profiles', models.ManyToManyField(related_name='student_families', to='students.StudentProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
