# Generated by Django 3.2.12 on 2022-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220712_1510'),
        ('parents', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='parent_profiles',
            field=models.ManyToManyField(related_name='families', to='parents.ParentProfile'),
        ),
        migrations.AlterField(
            model_name='family',
            name='student_profiles',
            field=models.ManyToManyField(related_name='families', to='students.StudentProfile'),
        ),
    ]
