# Generated by Django 3.2.12 on 2022-11-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_refactoring_history'),
        ('parents', '0003_added_history_records'),
        ('families', '0004_added_history_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFamily_student_profiles',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='families.family')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='families.historicalfamily')),
                ('studentprofile', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'HistoricalFamily_student_profiles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFamily_parent_profiles',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='families.family')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='families.historicalfamily')),
                ('parentprofile', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'HistoricalFamily_parent_profiles',
            },
        ),
    ]
