

# Generated by Django 3.2.3 on 2022-06-28 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees',
                                    to=settings.AUTH_USER_MODEL),
        ),

        migrations.AddField(
            model_name='employee',
            name='employee_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='employeess',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]

