

# Generated by Django 3.2.3 on 2022-06-28 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_profiles_for_employees(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    EmployeeProfile = apps.get_model("employees", "employeeprofile")
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias
    qs = User.objects.using(db_alias).all()
    for i in qs:
        employee_profile = EmployeeProfile()
        employee_profile.user = i
        employee_profile.save(using=db_alias)


def delete_employees_profiles(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    EmployeeProfile = apps.get_model("employees", "employeeprofile")
    Employee = apps.get_model("employees", "employee")
    db_alias = schema_editor.connection.alias
    EmployeeProfile.objects.using(db_alias).all().delete()
    qs = Employee.objects.using(db_alias).all()
    for i in qs:
        i.employee_profile = i.user
        i.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_employees'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_employees, delete_employees_profiles),

        migrations.AlterField(
            model_name='employee',
            name='employee_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees',
                                    to="employees.employeeprofile", default=None),
        ),
    ]
