
# Generated by Django 3.2.3 on 2022-06-28 12:34

from django.conf import settings
from django.db import migrations
from safedelete.config import DELETED_VISIBLE


def change_relations(apps, schema_editor):
    Employee = apps.get_model("employees", "employee")
    User = apps.get_model("users", "user")
    EmployeeProfile = apps.get_model("employees", "employeeprofile")

    db_alias = schema_editor.connection.alias
    qs = User.objects.using(db_alias).all(force_visibility=DELETED_VISIBLE)
    for i in qs:
        try:
            employee_profile = EmployeeProfile.objects.using(db_alias).get(user=i)
            employee = Employee.objects.using(db_alias).get(user=i)
            employee.employee_profile = employee_profile
            employee.save()
        except:
            pass


def revert_relations(apps, schema_editor):
    Employee = apps.get_model("employees", "employee")

    db_alias = schema_editor.connection.alias
    qs = Employee.objects.using(db_alias).all(force_visibility=DELETED_VISIBLE)
    for i in qs:
        i.user = i.employee_profile.user
        i.employee_profile = None
        i.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0005_change_to_employee'),
    ]

    operations = [
        migrations.RunPython(change_relations, revert_relations),
    ]
