# Generated by Django 3.2.12 on 2022-07-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('employees', '0007_alter_employee_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization'),
        ),
    ]
