# Generated by Django 3.2.12 on 2023-08-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_unique_together_squashed_0013_merge_20221205_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
