# Generated by Django 3.2.12 on 2024-06-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20230823_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('creator', 'creator'), ('director', 'director'), ('employee', 'employee'), ('view_only', 'view only')], default='employee', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='role',
            field=models.CharField(blank=True, choices=[('creator', 'creator'), ('director', 'director'), ('employee', 'employee'), ('view_only', 'view only')], default='employee', max_length=50, null=True),
        ),
    ]
