# Generated by Django 3.2.12 on 2022-09-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_position'),
        ('employees', '0009_employeeprofile_email'),
    ]

    operations = [
    ]
