# Generated by Django 3.2.12 on 2022-11-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20221029_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
