# Generated by Django 3.2.12 on 2022-12-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_added_history_records'),
        ('employees', '0012_alter_employee_unique_together'),
    ]

    operations = [
    ]
