# Generated by Django 3.2.12 on 2022-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
