# Generated by Django 3.2.12 on 2024-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0007_refactoring_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='creationtoken',
            name='otp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creationtoken',
            name='session',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
