# Generated by Django 3.2.12 on 2022-11-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_added_history_records_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='last_login_ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
