# Generated by Django 3.2.12 on 2022-11-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221108_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='last_login_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
