# Generated by Django 3.2.12 on 2022-11-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_added_history_records_with_fixes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfirebasenotificationtoken',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfirebasenotificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalCreationToken',
        ),
        migrations.DeleteModel(
            name='HistoricalFirebaseNotificationToken',
        ),
    ]
