# Generated by Django 3.2.12 on 2022-12-29 20:50

import config.settings.object_storage
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import rules.contrib.models
import uuid


class Migration(migrations.Migration):

    replaces = [('photos', '0001_initial'), ('photos', '0002_auto_20221030_2043'), ('photos', '0003_added_history_records'), ('photos', '0004_refactoring_history')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default=None, null=True, storage=config.settings.object_storage.ClientDocsStorage(), upload_to='')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
