# Generated by Django 3.2.12 on 2022-11-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_added_history_records'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPhoto',
        ),
    ]
