# Generated by Django 3.2.12 on 2025-05-24 17:42

import uuid
from decimal import Decimal

import django.utils.timezone
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreceipt',
            name='charged_this_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                      help_text='Сумма, начисленная за текущий месяц', max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='charged_this_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                      help_text='Сумма, начисленная за текущий месяц', max_digits=10),
        ),
        migrations.CreateModel(
            name='ReceiptService',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('institution', models.CharField(help_text='Institution code/name for this service', max_length=200)),
                ('service_name', models.CharField(help_text='Name of the specific service', max_length=300)),
                ('debt_at_month_start', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                            help_text='Debt at start of month for this service',
                                                            max_digits=10)),
                ('charged_this_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                           help_text='Amount charged this month for this service',
                                                           max_digits=10)),
                ('recalculation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                             help_text='Recalculation amount for this service',
                                                             max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                    help_text='Amount paid for this service', max_digits=10)),
                ('debt_at_next_month_start', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                                 help_text='Debt at start of next month for this service',
                                                                 max_digits=10)),
                ('prepayment',
                 models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prepayment for this service',
                                     max_digits=10)),
                ('service_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                                       help_text='Total amount due for this service', max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services',
                                              to='receipts.receipt')),
            ],
            options={
                'ordering': ['service_name'],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
