# Generated by Django 3.2.12 on 2025-05-24 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('receipts', '0002_auto_20250524_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreceipt',
            name='barcode_data',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='barcode_data',
        ),
    ]
