# Generated by Django 3.2.12 on 2025-05-26 07:21

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('receipts', '0003_auto_20250524_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptservice',
            name='charged_this_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                      help_text='Сумма, взимаемая в этом месяце за кружок', max_digits=10),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='debt_at_month_start',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                      help_text='Долг на начало месяца для этого кружка', max_digits=10),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='debt_at_next_month_start',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                      help_text='Долг на начало следующего месяца за кружок', max_digits=10),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='institution',
            field=models.CharField(help_text='Учебное учреждение', max_length=200),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сколько оплачено за кружок',
                                      max_digits=10),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Предоплата за кружок',
                                      max_digits=10),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='recalculation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                      help_text='Перерасчет в этом месяце за кружок', max_digits=10),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='service_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'),
                                      help_text='Общая сумма долга за кружок', max_digits=10),
        ),
        migrations.AlterField(
            model_name='receiptservice',
            name='service_name',
            field=models.CharField(help_text='Название кружка', max_length=300),
        ),
    ]
