# Generated by Django 3.2.12 on 2022-12-29 20:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('circles', '0001_initial'), ('circles', '0002_auto_20220728_1226'), ('circles', '0003_circle_location')]

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to='organizations.organization')),
                ('address', models.CharField(default='', max_length=255)),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(default='', max_length=2000)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
