# Generated by Django 3.2.12 on 2022-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20220728_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='circle',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=22, null=True),
        ),
    ]
