# Generated by Django 3.2.12 on 2023-03-14 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0006_auto_20230221_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='circle',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcircle',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalcircle',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
