# Generated by Django 3.2.12 on 2022-12-29 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('queries', '0001_initial'), ('queries', '0002_alter_query_status'), ('queries', '0003_auto_20220831_1959'), ('queries', '0004_auto_20221105_1715'), ('queries', '0005_auto_20221030_2043'), ('queries', '0006_auto_20221107_1947'), ('queries', '0007_added_history_records'), ('queries', '0008_refactoring_history')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(default=uuid.uuid4)),
                ('sender_id', models.UUIDField(default=uuid.uuid4)),
                ('body_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In Progress'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled')], default='SENT', max_length=200)),
                ('body_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_ct', to='contenttypes.contenttype')),
                ('recipient_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_ct', to='contenttypes.contenttype')),
                ('sender_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_ct', to='contenttypes.contenttype')),
                ('additional_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_ct', to='contenttypes.contenttype')),
                ('additional_id', models.UUIDField(default=uuid.uuid4)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'unique_together': set(),
            },
        ),
    ]
