# Generated by Django 3.2.12 on 2022-07-11 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(default=uuid.uuid4)),
                ('sender_id', models.UUIDField(default=uuid.uuid4)),
                ('body_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WAITING', 'Waiting'), ('NOT_ACCEPTED', 'Not accepted')], default='WAITING', max_length=200)),
                ('body_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_ct', to='contenttypes.contenttype')),
                ('recipient_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_ct', to='contenttypes.contenttype')),
                ('sender_ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_ct', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('recipient_ct', 'recipient_id', 'sender_ct', 'sender_id')},
            },
        ),
    ]
