# Generated by Django 3.2.12 on 2022-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In progress'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled')], default='SENT', max_length=200),
        ),
    ]
