# Generated by Django 3.2.12 on 2022-08-31 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('queries', '0002_alter_query_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='additional_ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_ct', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='query',
            name='additional_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='query',
            unique_together=set(),
        ),
    ]
