# Generated by Django 3.2.12 on 2024-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_historicalquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquery',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In Progress'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('CLOSED', 'Closed')], default='SENT', max_length=200),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In Progress'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('CLOSED', 'Closed')], default='SENT', max_length=200),
        ),
    ]
