# Generated by Django 3.2.12 on 2022-08-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_alter_query_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('SENT', 'Sent'), ('IN_PROGRESS', 'In Progress'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled'), ('TEST_STATUS', 'Test Status')], default='SENT', max_length=200),
        ),
    ]
