# Generated by Django 3.2.12 on 2022-11-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('queries', '0003_auto_20220831_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='additional_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_ct', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='query',
            name='body_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_ct', to='contenttypes.contenttype'),
        ),
    ]
