# Generated by Django 3.2.12 on 2022-07-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_examples', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentExample',
        ),
    ]
