# Generated by Django 3.2.12 on 2022-07-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import open_schools_platform.student_management.student_profile.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', open_schools_platform.student_management.student_profile.models.StudentProfileManager()),
            ],
        ),
    ]
