# Generated by Django 3.2.12 on 2023-07-07 18:05

from django.db import migrations, models
import django.utils.timezone
import rules.contrib.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('char_field', models.CharField(blank=True, max_length=256, null=True)),
                ('second_char_field', models.CharField(blank=True, max_length=256, null=True)),
                ('char_field_with_choices', models.CharField(blank=True, choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third')], max_length=256, null=True)),
                ('integer_field', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
