# Generated by Django 3.2.3 on 2022-06-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_randommodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomModel',
        ),
    ]
