# Generated by Django 3.2.12 on 2022-08-22 14:21

from django.db import migrations, models
import django.utils.timezone
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_delete_randommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_radius', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
