# Generated by Django 3.2.12 on 2022-08-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
