class SwaggerTags:
    ERRORS = "Errors"
    USER_MANAGEMENT_USERS = "User management. Users"
    USER_MANAGEMENT_AUTH = "User management. Authentication"
    ORGANIZATION_MANAGEMENT_ORGANIZATIONS = "Organization management. Organizations"
    ORGANIZATION_MANAGEMENT_EMPLOYEES = "Organization management. Employees"
    ORGANIZATION_MANAGEMENT_CIRCLES = "Organization management. Circles"
    PARENT_MANAGEMENT_FAMILIES = "Parent management. Families"
    PARENT_MANAGEMENT_PARENTS = "Parent management. Parents"
    STUDENT_MANAGEMENT_STUDENTS = "Student management. Students"
    QUERY_MANAGEMENT_QUERIES = "Query management. Queries"
    PHOTO_MANAGEMENT_PHOTOS = "Photos management. Photos"
    HISTORY_MANAGEMENT = "History management. User"
